from domain.models import User
from domain.repositories.user import UserRepository
from infrastructure.models import User as UserModel
from sqlalchemy.ext.asyncio import AsyncSession
from infrastructure.mappers import user_from_model
from sqlalchemy.future import select


class SQLAlchemyUserRepository(UserRepository):
    def __init__(self, session: AsyncSession):
        self.session = session

    async def get_by_id(self, user_id: str) -> User:
        user_model = await self.session.get(UserModel, user_id)
        return user_from_model(user_model) if user_model else None

    async def get_by_username(self, username: str) -> User:
        stmt = select(UserModel).filter_by(username=username)
        result = await self.session.execute(stmt)
        user_model = result.scalars().first()
        return user_from_model(user_model) if user_model else None

    async def create_user(self, username: str, hashed_password: str) -> User:
        user_entity = User.create_user(
            username=username, hashed_password=hashed_password
        )
        model = UserModel(
            username=user_entity.username, hashed_password=user_entity.hashed_password
        )
        self.session.add(model)
        await self.session.commit()
        await self.session.refresh(model)  # refresh to get autogenerated fields like id
        return user_from_model(model)

    async def save(self, user: User):
        user_orm = await self.session.get(UserModel, user.id)
        if user_orm:
            user_orm.hashed_password = user.hashed_password
            user_orm.username = user.username
            self.session.add(user_orm)
            await self.session.commit()
            return user
        else:
            return await self.create_user(user.username, user.hashed_password)
